source 'https://rubygems.org'

gem 'sinatra'
gem 'mongoid'
gem 'celluloid'
gem 'concurrent-ruby', require: 'concurrent'
gem 'dotenv'
gem 'pry-byebug'
gem 'stock_knight', path: 'vendor/cache/stock_knight'
gem 'unicorn'
gem 'terminal-table'
gem 'activesupport'
